# Generated by Django 4.2.16 on 2026-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
