# Generated by Django 4.2.16 on 2026-07-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_payment_status_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_RESTOCKED', 'Product Restocked'), ('CUSTOMER_CREATED', 'Customer Created'), ('SUPPLIER_CREATED', 'Supplier Created'), ('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_STATUS', 'Invoice Status Updated'), ('EMPLOYEE_ADDED', 'Employee Added'), ('BULK_IMPORT', 'Bulk Import Executed'), ('COMPANY_UPDATED', 'Company Details Updated'), ('GENERAL', 'General Event')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
