# Generated by Django 4.2.16 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_action_type_auditlog_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_terms',
            field=models.TextField(blank=True, default='Payment due within 15 days. Thank you for your business!'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
